@startuml test

actor Cliente

'--- GET /api/consultation/ ---
Cliente -> ConsultationController :[GET /getOne/{id}] getOne(id)
ConsultationController -> ConsultationService : obtenerEntidad(id)
ConsultationService -> ConsultationRepository : findById(id)
ConsultationRepository --> ConsultationService : entidad
ConsultationService -> ConsultationService : convertirAEntidadDTO(entidad)
ConsultationService -> ConsultationDTO : new()
ConsultationDTO --> ConsultationService : consultationDTO
ConsultationService --> ConsultationController : return consultationDTO
ConsultationController --> Cliente : return consultationDTO (JSON)

' --- POST /api/consultation/ ---
Cliente -> ConsultationController : [POST /create] createEntidad(consultationDTO)
ConsultationController -> ConsultationService : crearEntidad(consultationDTO)
ConsultationService -> ConsultationService : convertirADominio(consultationDTO)
ConsultationService -> Consultation : new()
ConsultationService -> ConsultationRepository : save(entidad)
ConsultationRepository --> ConsultationService : entidad
ConsultationService -> ConsultationService : convertirAEntidadDTO(entidad)
ConsultationService --> ConsultationController : return consultationDTO
ConsultationController --> Cliente : return consultationDTO (JSON)

' --- PUT /api/consultation/ ---
Cliente -> ConsultationController : [POST /update/{id}] updateEntidad(id, consultationDTO)
ConsultationController -> ConsultationService : actualizarEntidad(id, consultationDTO)
ConsultationService -> ConsultationRepository : findById(id)
ConsultationRepository --> ConsultationService : entidad
ConsultationService -> ConsultationService : convertirAEntidadDTO(entidad)
ConsultationService -> ConsultationDTO : new()
ConsultationDTO --> ConsultationService : consultationDTO
ConsultationService -> ConsultationService : convertirADominio(consultationDTO)
ConsultationService -> ConsultationRepository : update(entidad)
ConsultationRepository --> ConsultationService : entidad
ConsultationService -> ConsultationService : convertirAEntidadDTO(entidad)
ConsultationService --> ConsultationController : return consultationDTO
ConsultationController --> Cliente : return consultationDTO (JSON)

' --- DELETE /api/consultation/ ---
Cliente -> ConsultationController : [DELETE /delete/{id}] deleteEntidad(id)
ConsultationController -> ConsultationService : eliminarEntidad(id)
ConsultationService -> ConsultationRepository : deleteById(id)
ConsultationRepository --> ConsultationService : void
ConsultationService --> ConsultationController : void
ConsultationController --> Cliente : 204 No Content

@enduml
